// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeRoomie.Database;

#nullable disable

namespace OfficeRoomie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122131458_M01-initialmigration")]
    partial class M01initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OfficeRoomie.Models.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("permissoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("administradores");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Cartao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cliente_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("cvv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeDoTitular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroDoCartao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("validade")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("cliente_id");

                    b.ToTable("cartoes");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco_pais")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Reserva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("cartao_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cliente_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("data_reserva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hora_fim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hora_inicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("protocolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sala_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("cartao_id");

                    b.HasIndex("cliente_id");

                    b.HasIndex("sala_id");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Sala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("capacidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("salas");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Cartao", b =>
                {
                    b.HasOne("OfficeRoomie.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("OfficeRoomie.Models.Reserva", b =>
                {
                    b.HasOne("OfficeRoomie.Models.Cartao", "cartao")
                        .WithMany()
                        .HasForeignKey("cartao_id");

                    b.HasOne("OfficeRoomie.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeRoomie.Models.Sala", "sala")
                        .WithMany()
                        .HasForeignKey("sala_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cartao");

                    b.Navigation("cliente");

                    b.Navigation("sala");
                });
#pragma warning restore 612, 618
        }
    }
}
